AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'views/**/*'
    - 'Rakefile'
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
